services:
  postgres:
    image: postgres:16-alpine
    container_name: kynghesat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kynghesat
      POSTGRES_USER: kynghesat
      POSTGRES_PASSWORD: kynghesat
    ports:
      - "5433:5432"
    volumes:
      - kynghesat_pg_data:/var/lib/postgresql/data

volumes:
  kynghesat_pg_data:
